#! /bin/dash
# ------------------------------------------------------------------------------
# write_sdcard_img - uncompresses the img.gz file to a .img file and then
#                    writes the raw SD Card data
# ------------------------------------------------------------------------------

error_out () {
    echo "$1"
    exit 1
}

if [ "$(whoami)" != "root" ]; then
	error_out "Sorry, you are not root."
fi

# extract and validate device from command line arguments
if [ $# -ne 1 ]; then
  echo "usage: ./write_sdcard_img <device>" && exit
fi
device=$1;
if [ ! -b $device ]; then
  echo "$device: not found or no block device" && exit 1
fi

# ------------------------------------------------------------------------------

umount "${device}1"
umount "${device}2"
umount "${device}"

sleep 1

echo "-------------------------------------------------------------------------------"
echo "WARNING - If you type \"Yes\" to the prompt, this script"
echo "          will OVERWRITE the existing ev3dev.img file on the hard drive and"
echo "          will OVERWRITE any data on the /dev/ev3dev SD Card"
echo "-------------------------------------------------------------------------------"
echo

echo -n "   Type \"Yes\" to continue ... "
read YesNo

if [ ! "${YesNo}" = "Yes" ]; then
    error_out "\n    .. aborting, you typed \"${YesNo}\""
fi

# ------------------------------------------------------------------------------
# Unzip the raw SD Card image

cd ../ev3dev-rootfs

echo -n "   gunzipping the raw SD Card image - should take about 2 minutes..."

gunzip -k ev3dev.img.gz

echo " done."

echo    "   Writing the raw SD Card image - should take about 5 minutes..."

dd bs=4M if=ev3dev.img of=$device

if [ $? -gt 0 ]; then
    error_out "   SD Card image write failed"
else
    echo " done."
fi

echo " done."

cd ${OLDPWD}

echo "-------------------------------------------------------------------------------"
exit
