#! /bin/dash
# ------------------------------------------------------------------------------
# write_sdcard_img - uncompresses the img.gz file to a .img file and then
#                    writes the raw SD Card data
# ------------------------------------------------------------------------------

if [ "$(whoami)" != "root" ]; then
	echo "Sorry, you are not root." && exit 1
fi

# extract and validate device from command line arguments
if [ $# -ne 1 ]; then
  echo "usage: ./write_sdcard_img <device>" && exit
fi
device=$1;
if [ ! -b $device ]; then
  echo "error: $device: not found or no block device" && exit 1
fi

# abort if device is still mounted
if mount | grep "^$device" > /dev/null; then
  echo "error: $device: the following partitions are mounted:"
  mount | grep "^$device"
  echo "unmount manually and retry" && exit 1
fi

# ------------------------------------------------------------------------------

# prompt for card erase confirmation
echo "Warning - this script will erase all data on device $device"
read -p "  Continue? [y/N] " -r
if [[ ! "$REPLY" =~ ^[yY] ]]; then
  exit 1
fi

# ------------------------------------------------------------------------------
# Unzip the raw SD Card image

cd ../ev3dev-rootfs

echo -n "   gunzipping the raw SD Card image - should take about 2 minutes..."

gunzip -k ev3dev.img.gz

echo " done."

echo    "   Writing the raw SD Card image - should take about 5 minutes..."

dd bs=4M if=ev3dev.img of=$device

if [ $? -gt 0 ]; then
    echo "   SD Card image write failed" && exit 1
else
    echo " done."
fi

echo " done."

echo "-------------------------------------------------------------------------------"
